"""Add nullable shop_keeper_id to Product

Revision ID: 10b0d469b4a4
Revises: 8a63d893f4fa
Create Date: 2025-07-03 02:45:27.179923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b0d469b4a4'
down_revision = '8a63d893f4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('shop_keeper_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('shop_keeper_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
