"""Add shop_keeper_id to Product

Revision ID: 1f5583646bf3
Revises: d0184f218c25
Create Date: 2025-07-03 02:35:48.672775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5583646bf3'
down_revision = 'd0184f218c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_keeper_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['shop_keeper_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shop_keeper_id')

    # ### end Alembic commands ###
