"""Fix category relationship

Revision ID: 53197d1b796a
Revises: befb396cc9f9
Create Date: 2025-07-25 22:38:24.961051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53197d1b796a'
down_revision = 'befb396cc9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_on_offer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')
        batch_op.drop_column('is_on_offer')
        batch_op.drop_column('old_price')

    op.drop_table('categories')
    # ### end Alembic commands ###
