"""Make shop_keeper_id non-nullable

Revision ID: 8a63d893f4fa
Revises: 1f5583646bf3
Create Date: 2025-07-03 02:40:55.117317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a63d893f4fa'
down_revision = '1f5583646bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('shop_keeper_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('shop_keeper_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
