"""Add source_product_id to Product

Revision ID: befb396cc9f9
Revises: 10b0d469b4a4
Create Date: 2025-07-03 04:14:03.013642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'befb396cc9f9'
down_revision = '10b0d469b4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'products', ['source_product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_product_id')

    # ### end Alembic commands ###
